AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Resources:
  GeolocationFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      CodeUri: src/handler/
      Handler: index.handler
      Runtime: nodejs18.x
      Timeout: 10
      Events:
        GeolocationApi:
          Type: Api
          Properties:
            Path: /{postcode}
            Method: get

Outputs:
  GeolocationApi:
    Description: "API Gateway endpoint URL for GeolocationFunction"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/prod/"
  GeolocationFunction:
    Description: "Lambda Function ARN"
    Value: !GetAtt GeolocationFunction.Arn
